### ISSUE TITLE
Detached "everything" inventory is not restricted to player

### ISSUE THREAD

**Issue by Wuzzy2** [rollerozxa/chest_with_everything#1]
This mod is insecure because its detached inventory `everything` is not restricted to players. This means that unprivileged players could potentially abuse this.

Check out MTG's `creative` mod to learn how to correctly create a secure creative-like inventory.

**Comment by rollerozxa** [comment]
oh fuck-

Yeah that was a massive security oversight by me. I also realised that, since this is a chest node you place down, it needs protections against regular users on multiplayer servers being able to just grab and steal it and get unlimited items. So I basically restricted it behind the 'give' privilege, both for taking out items and opening the formspec in the first place, which fixes the issues.
